### ISSUE TITLE
Profile image displayed empty

### ISSUE THREAD

**Issue by unseenmagik** [Malarne/discord_cogs#2]
If a user types `[p]profile` and they have not registered, a blank profile image is shown. 

![image](https://user-images.githubusercontent.com/30931287/48193366-3ae17180-e342-11e8-92b9-955acdbcbdbc.png)

If a user is registered, then the infromation is displayed in the img. 

![image](https://user-images.githubusercontent.com/30931287/48193442-619fa800-e342-11e8-950a-e4d807c69241.png)

**Adjustments:**

There should be a check added to check if the user is Registered before posting the profile image. 
If they are not registered, post reply with "Please register with [p]register to view your profile and gain XP"

**Comment by Malarne** [comment]
can make that change, i made that command from an old embed to an image, and had no idea what to display for users not registered, gonna update that as soon as i open my pycharm aha
