### ISSUE TITLE
Roles not being issued. 

### ISSUE THREAD

**Issue by JamsRepos** [Malarne/discord_cogs#33]
Roles aren't being given to people leveling up. Yes, the bot has full administration powers. I'm wondering if the roles having "(lvl 10+)" in the names would break it, unsure.

The way they were added was 
`!levelerset roles add 10 @mentionedrole`

**Comment by Malarne** [comment]
check out if anything is thrown to your bot's console ?

**Comment by JamsRepos** [comment]
There's no errors however it seems to work temporarily. When I do `!levelerset setlevel 15 @Lubricant Jam` it gave me a role but then anything else I try after that it just doesn't give me a role.

What's the conditions in which it gives you a role?

**Comment by Malarne** [comment]
oh the user need to reach the exact level, not get setlevel'd

**Comment by JamsRepos** [comment]
Yeah that's what I was thinking. I assume if I set my XP one away from leveling up, it'll work? 

Also, we have periodic ranks, so one at level 5, 10, 20, etc. If I hit say level 17, will it try give me level 15 or does it disregard?

**Comment by Malarne** [comment]
it should work, and if you hit level 17, you should have went through lvl 15 so already have the lvl 15 role

**Comment by Malarne** [comment]
the cog isn't really handling fine the cheats aha

**Comment by JamsRepos** [comment]
Yeah no problem, I like to test things before I use them hence why it all makes sense now why things didn't work, cheers for the help.
