### ISSUE TITLE
[Request] Leveler System

### ISSUE THREAD

**Issue by riparoo** [Malarne/discord_cogs#44]
Hello I have recently started using your Leveler System and am loving it. I changed up the design myself but it works great. One thing I've noticed with the XP system though is that instead of the normal once you level your xp goes back to 0 and you climb to the next total you keep your previous XP and continue to the next max XP needed.

Is there any way you could make it at each level the XP reset to 0 and then you climb to the max XP needed for that level?

**Comment by Malarne** [comment]
You probably can do that pretty easily if you check out how i made the exp system, you'll just have to substract the xp needed for level -1 somewhere around line 176 of leveler.py (there is a function for getting needed xp for a level inside userprofile.py

**Comment by riparoo** [comment]
Ah okay great thank you very much I will look in to it now =)
