### ISSUE TITLE
[oBoobs] request

### ISSUE THREAD

**Issue by theMisteryDE** [Malarne/discord_cogs#64]
Since my Bot runs on 22 Servers by now with nearly 2000 Members, I'm running Toby's errorlogs cog.

Lately there is this one curious User, trying to get boobs and ass with DMing the Bot. And everytime I get a new errorlog sent to my Server :D 

Could you make it so, that in DM there is a "this command does not work in DM" response? Or something else, all I care so far is to stop getting the errorlogs xD

**Comment by Malarne** [comment]
sure no problem

**Comment by theMisteryDE** [comment]
thanks, works fine :)
